# Local HS dataset for the MVP demo (~100 lines across major consumer verticals).
# NOTE: duty rates are ILLUSTRATIVE for the demo only — not authoritative tariffs.
# Each entry: code, description, keywords (drive matching), chapter,
# us_duty_rate / ca_duty_rate (general MFN, as a fraction), fta (preferential rate).

HS_DATA = [
    # ====================== APPAREL — KNITTED (Ch. 61) ======================
    {"code": "6109.10.00.10", "description": "T-shirts, singlets, knitted, of cotton",
     "keywords": ["t-shirt", "tshirt", "tee", "shirt", "cotton", "knitted", "knit", "apparel", "top"],
     "chapter": "61", "us_duty_rate": 0.165, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6109.90.10.07", "description": "T-shirts, singlets, knitted, of man-made fibers",
     "keywords": ["t-shirt", "tshirt", "tee", "shirt", "polyester", "synthetic", "knitted", "apparel"],
     "chapter": "61", "us_duty_rate": 0.32, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6110.20.20.79", "description": "Sweaters, pullovers, knitted, of cotton",
     "keywords": ["sweater", "pullover", "jumper", "hoodie", "sweatshirt", "cotton", "knitted", "apparel"],
     "chapter": "61", "us_duty_rate": 0.165, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6110.30.30.53", "description": "Sweaters, pullovers, knitted, of man-made fibers",
     "keywords": ["sweater", "pullover", "fleece", "hoodie", "polyester", "synthetic", "knitted", "apparel"],
     "chapter": "61", "us_duty_rate": 0.32, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6105.10.00.10", "description": "Men's shirts, knitted, of cotton (polos)",
     "keywords": ["polo", "shirt", "knitted", "cotton", "mens", "apparel"],
     "chapter": "61", "us_duty_rate": 0.197, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6104.63.20.11", "description": "Women's trousers/leggings, knitted, of synthetic fibers",
     "keywords": ["leggings", "trousers", "pants", "womens", "synthetic", "polyester", "knitted", "activewear"],
     "chapter": "61", "us_duty_rate": 0.286, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6115.96.90.00", "description": "Socks and hosiery, knitted, of synthetic fibers",
     "keywords": ["socks", "hosiery", "stockings", "synthetic", "knitted", "apparel"],
     "chapter": "61", "us_duty_rate": 0.149, "ca_duty_rate": 0.16, "fta": {"USMCA": 0.0}},
    {"code": "6111.20.60.70", "description": "Babies' garments and accessories, knitted, of cotton",
     "keywords": ["baby", "babies", "infant", "onesie", "romper", "cotton", "knitted", "apparel"],
     "chapter": "61", "us_duty_rate": 0.083, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},

    # ====================== APPAREL — WOVEN (Ch. 62) ======================
    {"code": "6203.42.40.16", "description": "Men's trousers and shorts, of cotton, woven",
     "keywords": ["trousers", "pants", "shorts", "chinos", "jeans", "cotton", "woven", "mens", "apparel"],
     "chapter": "62", "us_duty_rate": 0.166, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6203.43.40.10", "description": "Men's trousers, of synthetic fibers, woven",
     "keywords": ["trousers", "pants", "shorts", "synthetic", "polyester", "woven", "mens", "apparel"],
     "chapter": "62", "us_duty_rate": 0.276, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6204.62.80.11", "description": "Women's trousers and shorts, of cotton, woven",
     "keywords": ["trousers", "pants", "shorts", "womens", "ladies", "cotton", "woven", "apparel"],
     "chapter": "62", "us_duty_rate": 0.166, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6204.44.40.00", "description": "Women's dresses, of artificial fibers, woven",
     "keywords": ["dress", "gown", "womens", "ladies", "synthetic", "woven", "apparel"],
     "chapter": "62", "us_duty_rate": 0.16, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6205.20.20.51", "description": "Men's shirts, of cotton, woven",
     "keywords": ["shirt", "dress", "buttondown", "cotton", "woven", "mens", "apparel"],
     "chapter": "62", "us_duty_rate": 0.199, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6206.30.30.40", "description": "Women's blouses and shirts, of cotton, woven",
     "keywords": ["blouse", "shirt", "top", "womens", "ladies", "cotton", "woven", "apparel"],
     "chapter": "62", "us_duty_rate": 0.153, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6202.30.20.10", "description": "Women's overcoats, anoraks, of man-made fibers",
     "keywords": ["jacket", "coat", "overcoat", "anorak", "windbreaker", "parka", "womens", "polyester", "apparel"],
     "chapter": "62", "us_duty_rate": 0.275, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6201.40.70.11", "description": "Men's anoraks and windbreakers, of man-made fibers",
     "keywords": ["jacket", "coat", "anorak", "windbreaker", "parka", "mens", "polyester", "apparel"],
     "chapter": "62", "us_duty_rate": 0.275, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6217.10.95.30", "description": "Clothing accessories (scarves, ties), woven",
     "keywords": ["scarf", "tie", "necktie", "accessory", "woven", "apparel"],
     "chapter": "62", "us_duty_rate": 0.149, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},

    # ====================== HOME TEXTILES (Ch. 63) ======================
    {"code": "6302.31.90.50", "description": "Bed linen, of cotton, woven",
     "keywords": ["bedsheet", "sheet", "bedding", "linen", "duvet", "pillowcase", "cotton", "home"],
     "chapter": "63", "us_duty_rate": 0.069, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6302.60.00.20", "description": "Toilet and kitchen linen, of cotton terry (towels)",
     "keywords": ["towel", "terry", "bath", "kitchen", "linen", "cotton", "home"],
     "chapter": "63", "us_duty_rate": 0.092, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6307.90.98.91", "description": "Made-up textile articles, other (face masks, misc.)",
     "keywords": ["textile", "article", "mask", "cloth", "rag", "misc", "home"],
     "chapter": "63", "us_duty_rate": 0.07, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6304.92.00.00", "description": "Furnishing articles, of cotton (cushion covers, throws)",
     "keywords": ["cushion", "cover", "throw", "blanket", "furnishing", "cotton", "home", "decor"],
     "chapter": "63", "us_duty_rate": 0.063, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},

    # ====================== FOOTWEAR (Ch. 64) ======================
    {"code": "6403.99.60.75", "description": "Footwear with leather uppers, rubber/plastic soles",
     "keywords": ["shoes", "footwear", "sneakers", "leather", "boots", "loafers"],
     "chapter": "64", "us_duty_rate": 0.085, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6404.11.90.20", "description": "Sports footwear with textile uppers, rubber/plastic soles",
     "keywords": ["sneakers", "trainers", "running", "shoes", "footwear", "textile", "sports", "athletic"],
     "chapter": "64", "us_duty_rate": 0.20, "ca_duty_rate": 0.18, "fta": {"USMCA": 0.0}},
    {"code": "6402.99.31.00", "description": "Footwear with rubber or plastic uppers and soles",
     "keywords": ["sandals", "flipflops", "rubber", "plastic", "slippers", "shoes", "footwear"],
     "chapter": "64", "us_duty_rate": 0.06, "ca_duty_rate": 0.16, "fta": {"USMCA": 0.0}},
    {"code": "6401.92.90.00", "description": "Waterproof footwear, rubber/plastic (rain boots)",
     "keywords": ["boots", "rain", "waterproof", "rubber", "wellington", "footwear"],
     "chapter": "64", "us_duty_rate": 0.37, "ca_duty_rate": 0.20, "fta": {"USMCA": 0.0}},

    # ====================== BAGS & LUGGAGE (4202) ======================
    {"code": "4202.12.80.00", "description": "Suitcases/briefcases with outer surface of textiles",
     "keywords": ["suitcase", "luggage", "briefcase", "trunk", "textile", "travel", "bag"],
     "chapter": "42", "us_duty_rate": 0.175, "ca_duty_rate": 0.11, "fta": {"USMCA": 0.0}},
    {"code": "4202.12.21.00", "description": "Suitcases/briefcases with outer surface of plastics",
     "keywords": ["suitcase", "luggage", "hardshell", "plastic", "travel", "spinner", "bag"],
     "chapter": "42", "us_duty_rate": 0.20, "ca_duty_rate": 0.155, "fta": {"USMCA": 0.0}},
    {"code": "4202.92.31.20", "description": "Backpacks with outer surface of textile materials",
     "keywords": ["backpack", "rucksack", "daypack", "nylon", "polyester", "textile", "bag"],
     "chapter": "42", "us_duty_rate": 0.176, "ca_duty_rate": 0.11, "fta": {"USMCA": 0.0}},
    {"code": "4202.21.90.00", "description": "Handbags with outer surface of leather",
     "keywords": ["handbag", "purse", "tote", "clutch", "leather", "bag"],
     "chapter": "42", "us_duty_rate": 0.09, "ca_duty_rate": 0.11, "fta": {"USMCA": 0.0}},
    {"code": "4202.22.15.00", "description": "Handbags with outer surface of plastic sheeting",
     "keywords": ["handbag", "purse", "tote", "plastic", "vinyl", "pvc", "bag"],
     "chapter": "42", "us_duty_rate": 0.16, "ca_duty_rate": 0.11, "fta": {"USMCA": 0.0}},
    {"code": "4202.32.99.00", "description": "Wallets/pouches for the pocket or handbag, other",
     "keywords": ["wallet", "pouch", "cardholder", "purse", "small", "accessory", "bag"],
     "chapter": "42", "us_duty_rate": 0.20, "ca_duty_rate": 0.085, "fta": {"USMCA": 0.0}},

    # ====================== PLASTICS & HOUSEHOLD (Ch. 39) ======================
    {"code": "3924.10.40.00", "description": "Tableware and kitchenware, of plastics",
     "keywords": ["plastic", "tableware", "kitchenware", "cup", "plate", "bowl", "container", "tupperware"],
     "chapter": "39", "us_duty_rate": 0.034, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3924.90.56.50", "description": "Other household articles, of plastics",
     "keywords": ["plastic", "household", "organizer", "tray", "basket", "holder", "article"],
     "chapter": "39", "us_duty_rate": 0.034, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3926.20.90.50", "description": "Articles of apparel and accessories, of plastics",
     "keywords": ["plastic", "raincoat", "apron", "gloves", "apparel", "accessory"],
     "chapter": "39", "us_duty_rate": 0.05, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3926.40.00.90", "description": "Statuettes and ornamental articles, of plastics",
     "keywords": ["plastic", "ornament", "statuette", "figurine", "decor", "decoration"],
     "chapter": "39", "us_duty_rate": 0.053, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3926.90.99.89", "description": "Other articles of plastics",
     "keywords": ["plastic", "article", "accessory", "fitting", "misc", "part"],
     "chapter": "39", "us_duty_rate": 0.053, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3923.21.00.95", "description": "Sacks and bags, of polymers of ethylene (plastic)",
     "keywords": ["plastic", "bag", "sack", "pouch", "packaging", "polyethylene", "poly", "ziplock"],
     "chapter": "39", "us_duty_rate": 0.03, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3922.10.00.00", "description": "Baths, sinks, washbasins, of plastics",
     "keywords": ["plastic", "bath", "sink", "washbasin", "tub", "bathroom"],
     "chapter": "39", "us_duty_rate": 0.063, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3919.90.50.60", "description": "Self-adhesive plates/sheets/film, of plastics",
     "keywords": ["plastic", "adhesive", "sticker", "label", "film", "tape", "sheet"],
     "chapter": "39", "us_duty_rate": 0.058, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},

    # ====================== ELECTRONICS (Ch. 84 / 85) ======================
    {"code": "8471.30.01.00", "description": "Portable digital computers (laptops), <10kg",
     "keywords": ["laptop", "notebook", "computer", "ultrabook", "macbook", "chromebook", "pc"],
     "chapter": "84", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8471.60.20.00", "description": "Keyboards and input units for computers",
     "keywords": ["keyboard", "mouse", "input", "trackpad", "computer", "peripheral"],
     "chapter": "84", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8471.70.50.65", "description": "Storage units for computers (hard drives)",
     "keywords": ["harddrive", "hdd", "storage", "disk", "drive", "computer"],
     "chapter": "84", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8473.30.11.40", "description": "Parts and accessories of computers (printed circuit assemblies)",
     "keywords": ["motherboard", "circuit", "pcb", "card", "ram", "component", "part", "computer"],
     "chapter": "84", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8443.31.00.00", "description": "Printers/copiers/fax combination machines",
     "keywords": ["printer", "copier", "scanner", "fax", "multifunction", "inkjet"],
     "chapter": "84", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8517.13.00.00", "description": "Smartphones",
     "keywords": ["smartphone", "phone", "mobile", "iphone", "android", "cellphone", "cell"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8517.62.00.90", "description": "Routers, modems, networking apparatus",
     "keywords": ["router", "modem", "network", "wifi", "switch", "gateway", "networking"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8518.30.20.00", "description": "Headphones and earphones",
     "keywords": ["headphones", "earphones", "earbuds", "headset", "airpods", "audio"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8518.22.00.00", "description": "Multiple loudspeakers in single enclosure (speakers)",
     "keywords": ["speaker", "loudspeaker", "soundbar", "bluetooth", "audio"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8504.40.85.00", "description": "Static converters / power adapters and chargers",
     "keywords": ["charger", "adapter", "power", "supply", "converter", "usb", "plug"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8507.60.00.20", "description": "Lithium-ion batteries / power banks",
     "keywords": ["battery", "powerbank", "lithium", "cell", "rechargeable", "power"],
     "chapter": "85", "us_duty_rate": 0.034, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8523.51.00.00", "description": "Solid-state non-volatile storage (USB flash, SSD)",
     "keywords": ["usb", "flash", "drive", "ssd", "storage", "memory", "stick", "sd"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8544.42.90.90", "description": "Insulated electric cables/cords fitted with connectors",
     "keywords": ["cable", "cord", "wire", "connector", "usb", "hdmi", "charging", "lead"],
     "chapter": "85", "us_duty_rate": 0.026, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8528.72.64.00", "description": "Television receivers, color, flat panel",
     "keywords": ["television", "tv", "monitor", "screen", "display", "led", "oled"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.05, "fta": {"USMCA": 0.0}},
    {"code": "8525.81.20.00", "description": "Digital cameras and video camera recorders",
     "keywords": ["camera", "webcam", "video", "recorder", "dslr", "gopro", "photo"],
     "chapter": "85", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},

    # ====================== KITCHEN: CERAMIC / GLASS / METAL (69/70/73/76/82) ===========
    {"code": "6912.00.48.10", "description": "Ceramic tableware/kitchenware (non-porcelain)",
     "keywords": ["ceramic", "mug", "plate", "bowl", "dish", "tableware", "stoneware", "kitchenware"],
     "chapter": "69", "us_duty_rate": 0.095, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "6911.10.10.00", "description": "Porcelain or china tableware and kitchenware",
     "keywords": ["porcelain", "china", "fine", "plate", "bowl", "dish", "tableware"],
     "chapter": "69", "us_duty_rate": 0.26, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "7013.42.00.00", "description": "Glassware for table/kitchen, low thermal expansion glass",
     "keywords": ["glass", "glassware", "tumbler", "cup", "jar", "kitchen", "drinkware"],
     "chapter": "70", "us_duty_rate": 0.075, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "7013.49.20.00", "description": "Glassware for table/kitchen, other (pressed/blown)",
     "keywords": ["glass", "glassware", "vase", "bowl", "decanter", "kitchen", "drinkware"],
     "chapter": "70", "us_duty_rate": 0.225, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "7323.93.00.80", "description": "Kitchen/table articles of stainless steel",
     "keywords": ["stainless", "steel", "metal", "pot", "pan", "cutlery", "kitchenware", "bottle", "flask"],
     "chapter": "73", "us_duty_rate": 0.02, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "7615.10.71.25", "description": "Cooking/kitchen articles of aluminum (cookware)",
     "keywords": ["aluminum", "aluminium", "cookware", "pot", "pan", "skillet", "kitchenware"],
     "chapter": "76", "us_duty_rate": 0.031, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "8215.20.00.00", "description": "Cutlery sets (spoons, forks) of base metal",
     "keywords": ["cutlery", "flatware", "spoon", "fork", "utensil", "metal", "kitchen"],
     "chapter": "82", "us_duty_rate": 0.07, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8211.91.50.00", "description": "Table knives with fixed blades (kitchen)",
     "keywords": ["knife", "knives", "kitchen", "chef", "blade", "steel", "cutlery"],
     "chapter": "82", "us_duty_rate": 0.007, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},

    # ====================== FURNITURE & LIGHTING (Ch. 94) ======================
    {"code": "9403.60.80.93", "description": "Wooden furniture (other), household",
     "keywords": ["furniture", "table", "desk", "cabinet", "shelf", "dresser", "wooden", "wood"],
     "chapter": "94", "us_duty_rate": 0.0, "ca_duty_rate": 0.095, "fta": {"USMCA": 0.0}},
    {"code": "9403.20.00.50", "description": "Metal furniture (other), household",
     "keywords": ["furniture", "metal", "steel", "table", "rack", "shelf", "frame"],
     "chapter": "94", "us_duty_rate": 0.0, "ca_duty_rate": 0.08, "fta": {"USMCA": 0.0}},
    {"code": "9401.61.40.11", "description": "Upholstered seats with wooden frames (chairs)",
     "keywords": ["chair", "seat", "sofa", "couch", "armchair", "upholstered", "furniture"],
     "chapter": "94", "us_duty_rate": 0.0, "ca_duty_rate": 0.095, "fta": {"USMCA": 0.0}},
    {"code": "9401.71.00.31", "description": "Upholstered seats with metal frames (office chairs)",
     "keywords": ["chair", "seat", "office", "swivel", "metal", "upholstered", "furniture"],
     "chapter": "94", "us_duty_rate": 0.0, "ca_duty_rate": 0.08, "fta": {"USMCA": 0.0}},
    {"code": "9404.21.00.00", "description": "Mattresses of cellular rubber or plastics",
     "keywords": ["mattress", "foam", "memory", "bed", "cushion", "topper"],
     "chapter": "94", "us_duty_rate": 0.03, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9405.42.84.10", "description": "LED lamps and lighting fittings, electric",
     "keywords": ["lamp", "light", "led", "lighting", "fixture", "bulb", "luminaire"],
     "chapter": "94", "us_duty_rate": 0.039, "ca_duty_rate": 0.07, "fta": {"USMCA": 0.0}},
    {"code": "9403.70.80.31", "description": "Furniture of plastics, household",
     "keywords": ["furniture", "plastic", "chair", "table", "stool", "outdoor"],
     "chapter": "94", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},

    # ====================== TOOLS & HARDWARE (Ch. 82 / 83) ======================
    {"code": "8205.40.00.00", "description": "Screwdrivers (hand tools)",
     "keywords": ["screwdriver", "tool", "handtool", "driver", "steel"],
     "chapter": "82", "us_duty_rate": 0.062, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8205.20.60.00", "description": "Hammers and sledge hammers (hand tools)",
     "keywords": ["hammer", "mallet", "tool", "handtool", "steel"],
     "chapter": "82", "us_duty_rate": 0.066, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8204.11.00.00", "description": "Hand-operated spanners and wrenches, non-adjustable",
     "keywords": ["wrench", "spanner", "socket", "tool", "handtool", "steel"],
     "chapter": "82", "us_duty_rate": 0.09, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8201.50.00.00", "description": "Secateurs and pruners (one-handed garden tools)",
     "keywords": ["pruner", "secateur", "shears", "garden", "tool", "clipper"],
     "chapter": "82", "us_duty_rate": 0.01, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8211.92.40.00", "description": "Knives with fixed blades (other)",
     "keywords": ["knife", "knives", "blade", "cutlery", "tool", "steel", "pocket"],
     "chapter": "82", "us_duty_rate": 0.01, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "8301.10.90.00", "description": "Padlocks of base metal",
     "keywords": ["padlock", "lock", "security", "metal", "hardware"],
     "chapter": "83", "us_duty_rate": 0.038, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},

    # ====================== TOYS, GAMES & SPORTS (Ch. 95) ======================
    {"code": "9503.00.00.90", "description": "Toys (other), incl. stuffed and wheeled toys",
     "keywords": ["toy", "toys", "plush", "doll", "stuffed", "kids", "children"],
     "chapter": "95", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9503.00.00.73", "description": "Toys: construction sets and building blocks",
     "keywords": ["blocks", "lego", "construction", "building", "bricks", "toy", "kids"],
     "chapter": "95", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9504.50.00.00", "description": "Video game consoles and machines",
     "keywords": ["console", "videogame", "gaming", "playstation", "xbox", "nintendo", "controller"],
     "chapter": "95", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9506.62.80.20", "description": "Inflatable balls (sports)",
     "keywords": ["ball", "football", "soccer", "basketball", "sports", "inflatable"],
     "chapter": "95", "us_duty_rate": 0.048, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9506.91.00.30", "description": "Exercise and fitness equipment (gym articles)",
     "keywords": ["fitness", "gym", "exercise", "dumbbell", "yoga", "weights", "treadmill", "sports"],
     "chapter": "95", "us_duty_rate": 0.046, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9503.00.00.71", "description": "Toys representing animals/non-human creatures, stuffed",
     "keywords": ["plush", "stuffed", "teddy", "animal", "toy", "soft", "kids"],
     "chapter": "95", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},

    # ====================== COSMETICS & PERSONAL CARE (Ch. 33 / 34) ===========
    {"code": "3304.99.50.00", "description": "Beauty/skin care preparations (creams, lotions)",
     "keywords": ["cream", "lotion", "skincare", "cosmetic", "moisturizer", "serum", "beauty"],
     "chapter": "33", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3304.20.00.00", "description": "Eye make-up preparations",
     "keywords": ["mascara", "eyeshadow", "eyeliner", "makeup", "cosmetic", "eye", "beauty"],
     "chapter": "33", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3305.10.00.00", "description": "Shampoos",
     "keywords": ["shampoo", "hair", "wash", "haircare", "conditioner"],
     "chapter": "33", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3303.00.30.00", "description": "Perfumes and toilet waters",
     "keywords": ["perfume", "fragrance", "cologne", "scent", "eau", "toilet"],
     "chapter": "33", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3401.11.50.00", "description": "Soap for toilet use (bars)",
     "keywords": ["soap", "bar", "cleanser", "wash", "toilet", "personal"],
     "chapter": "34", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "3306.10.00.00", "description": "Dentifrices (toothpaste)",
     "keywords": ["toothpaste", "dentifrice", "dental", "oral", "teeth"],
     "chapter": "33", "us_duty_rate": 0.0, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},

    # ====================== MISC CONSUMER GOODS ======================
    {"code": "9102.11.25.00", "description": "Wrist watches, battery, with mechanical display",
     "keywords": ["watch", "wristwatch", "timepiece", "quartz", "analog"],
     "chapter": "91", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "6601.10.00.00", "description": "Garden or similar umbrellas",
     "keywords": ["umbrella", "parasol", "garden", "patio", "sunshade"],
     "chapter": "66", "us_duty_rate": 0.064, "ca_duty_rate": 0.065, "fta": {"USMCA": 0.0}},
    {"code": "9608.10.00.00", "description": "Ball point pens",
     "keywords": ["pen", "ballpoint", "stationery", "writing"],
     "chapter": "96", "us_duty_rate": 0.008, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "4819.20.00.40", "description": "Folding cartons/boxes of non-corrugated paper",
     "keywords": ["box", "carton", "packaging", "paper", "cardboard", "gift"],
     "chapter": "48", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
    {"code": "9617.00.10.00", "description": "Vacuum flasks and other vacuum vessels",
     "keywords": ["flask", "thermos", "vacuum", "insulated", "bottle", "tumbler"],
     "chapter": "96", "us_duty_rate": 0.072, "ca_duty_rate": 0.07, "fta": {"USMCA": 0.0}},
    {"code": "4203.29.30.00", "description": "Gloves of leather (other than sports)",
     "keywords": ["gloves", "leather", "mittens", "accessory"],
     "chapter": "42", "us_duty_rate": 0.14, "ca_duty_rate": 0.155, "fta": {"USMCA": 0.0}},
    {"code": "7117.19.90.00", "description": "Imitation jewelry of base metal",
     "keywords": ["jewelry", "jewellery", "necklace", "bracelet", "earrings", "ring", "imitation"],
     "chapter": "71", "us_duty_rate": 0.11, "ca_duty_rate": 0.085, "fta": {"USMCA": 0.0}},
    {"code": "4911.10.00.80", "description": "Printed advertising material, catalogues",
     "keywords": ["printed", "catalogue", "brochure", "flyer", "advertising", "paper"],
     "chapter": "49", "us_duty_rate": 0.0, "ca_duty_rate": 0.0, "fta": {"USMCA": 0.0}},
]

# Fast lookup by code
CODE_INDEX = {e["code"]: e for e in HS_DATA}
